### ISSUE TITLE
hosted script ?

### ISSUE THREAD

**Issue by carefulcomputer** [devin2712/myturn-monitor#1]
This is awesome script. Are you planning to host this script in lambda and publish the json on a s3 bucket ?
Reason I ask is, I currently do puppeteer based web scraper to get data myturn and notify folks about availability on their phones. If you can run your script on lambda and publish json every X minutes. I could read off published JSON and publish notification in my (and other) community. Would you be willing to join hands to help get vaccine in hands of more people ?

**Comment by devin2712** [comment]
@carefulcomputer Thanks! Glad you were able to find this. 

I have a test deployment updating this endpoint: https://mtcavax.s3-us-west-1.amazonaws.com/data.json - for now, only running once a day so that I don't spam MyTurn (From your puppeteer project, I see that you already are cautious as well about running these things as well).

Feel free to read from that endpoint for now to adapt your project and let me know how I can help.

I also published this earlier: https://github.com/devin2712/our-turn/tree/master/california-myturn as the first iteration of my own personal project which seems similar to what you're doing already. It's more costly, as you're aware, due to the eligibility checks but it integrates with Airtable/Twilio for a full notification system.

Not sure how much you've dug into the MyTurn edge cases but I tried to document some of the nuances in the [README](https://github.com/devin2712/myturn-monitor#myturn-data-collection-methodology--assumptions). Feel free to open a PR if you find something else. The quick summary is that `hasAvailabilities` will be `true` in my JSON payload if and only if they show availabilities for both doses; otherwise, you'd send a notification and the person won't actually be able to book on MyTurn.

**Comment by carefulcomputer** [comment]
@devin2712 thanks for comments. BTW, recently I found that some of myturn servers will return 405 if number of headers is not exactly 3 !! Was almost tearing my hair out until i found that it was 'number' of headers. If you ever hit that issue, try sending 3 headers.

**Comment by carefulcomputer** [comment]
Couple of suggestions :
1)  appointments run out in few hours, so once a day check will be grossly out of date. I have found once an hour to be good balance.
2) several myturn sites have started single dose J&J vaccine. (e.g Oakland Coliseum)
